### ISSUE TITLE
Training on a custom dataset

### ISSUE THREAD

**Issue by cspearl** [branislavhesko/segmentation_framework#3]
I am going for a binary segmentation on a custom dataset masks are black and white(2 classes).
I have made the changes in config.py as mentioned but I am getting the following error:

INFO: [31/08/2021 01:39:48] [TrainModel:143-         _initialize()] DeepLabv3p
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "train.py", line 179, in <module>
    trainer = TrainModel(Configuration())
  File "train.py", line 41, in __init__
    self._initialize()
  File "train.py", line 148, in _initialize
    self.loader_train, self.loader_val = get_data_loaders(self._config)
  File "/content/gdrive/My Drive/seg-frame/loaders/get_data_loader.py", line 23, in get_data_loaders
    shuffle=True, num_workers=config.NUM_WORKERS)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 270, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/sampler.py", line 103, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by branislavhesko** [comment]
Hello.
Sorry for replying this late, I have a lot of work these days.
What is your folder structure? I will try to help you as much as possible.

Apparently, algorithm is unable to find images.

Cheers,
Branislav Hesko
